sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 4237
    database: sky_take_out
    username: root
    password: Payton521!
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tFcYE1tVytbkpcmncBa
    access-key-secret: 6teKtdUcmfyMCn3ryXlTFlb5BWCqh7
    bucket-name: take-out-management
  redis:
      host: localhost
      port: 6379
      password: 123456
  wechat:
    appid: wxedaec105b663299f
    secret: 3d678f53361d469390b1dc38ec9820af
  baidu:
    ak: 0ZkoHUdwz0WKS4biITJZpnIB24ytmM8Q
  shop:
    address: 北京市海淀区上地十街10号